[package]
name = "wisp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true

[[bin]]
name = "wisp"
path = "src/main.rs"

[dependencies]
wisp-core = { path = "../wisp-core" }
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
indicatif = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
