[package]
name = "wisp-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
wisp-core = { path = "../crates/wisp-core" }
tokio = { workspace = true }
tokio-util = { version = "0.7" }
anyhow = { workspace = true }
rfd = "0.15"
dirs = { workspace = true }
