[package]
name = "wisp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core protocol for Wisp: QUIC transport, mDNS discovery, BLAKE3-verified transfer."

[dependencies]
tokio = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
rcgen = { workspace = true }
blake3 = { workspace = true }
mdns-sd = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
indicatif = { workspace = true }
local-ip-address = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
spake2 = { workspace = true }
subtle = { workspace = true }
tracing = { workspace = true }
